apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/openplan-simulation-server-sim-network: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: MVS_DEV_VERSION
            - name: MVS_OPEN_PLAN_VERSION
          image: "eidaenrgy/API-openplan-simulation-server:latest"
          name: web
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
