apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - env:
            - name: MVS_DEV_VERSION
              value: 1.1.0
            - name: MVS_OPEN_PLAN_VERSION
              value: 1.1.0
            - name: CELERY_BROKER_URL
              value: redis.mvs.svc.cluster.local
            - name: CELERY_RESULT_BACKEND
              value: redis.mvs.svc.cluster.local
          image: "eidaenrgy/api-openplan-simulation-server:latest"
          name: web
          ports:
            - containerPort: 5001

      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

  type: ClusterIP
