apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: worker-dev
  name: worker-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker-dev
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/openplan-simulation-server-sim-network: "true"
        io.kompose.service: worker-dev
    spec:
      containers:
        - env:
            - name: CELERY_TASK_NAME
              value: dev
          image: "eidaenrgy/openplan-simulation-server:latest"
          name: worker-dev
          resources: {}
      restartPolicy: Always
status: {}
