apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-open-plan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-open-plan
  template:
    metadata:
      labels:
        app: worker-open-plan
    spec:
      containers:
        - name: worker-open-plan
          image: "eidaenrgy/openplan-simulation-server:latest"
          env:
            - name: CELERY_TASK_NAME
              value: open_plan
            - name: MVS_OPEN_PLAN_VERSION
              value: 1.1.0
            - name: CELERY_BROKER_URL
              value: redis://redis.mvs.svc.cluster.local
            - name: CELERY_RESULT_BACKEND
              value: redis://redis.mvs.svc.cluster.local
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: worker-open-plan
spec:
  selector:
    app: worker-open-plan
  ports:
    - protocol: TCP
      port: 5002 # Assuming the port used by worker-open-plan
      targetPort: 5002
  type: ClusterIP
